# Generated by Django 4.1.4 on 2022-12-27 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notepp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(blank=True, default=datetime.datetime(2022, 12, 27, 17, 6, 12, 273761))),
                ('title', models.CharField(max_length=100)),
                ('opt', models.CharField(max_length=100)),
                ('myfile', models.FileField(upload_to='Myfiles')),
                ('comments', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='usersignup',
            name='created',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 12, 27, 17, 6, 12, 273761)),
        ),
    ]
